import "./globals.css";

export const metadata = {
  title: "ＦＪＢＣ-補課系統",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen bg-gray-100">{children}</body>
    </html>
  );
}
